In [7]:
import numpy as np

In [8]:
#创造数组
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [10]:
print(np.__version__)
#输出np的版本

1.15.1


In [11]:
#numpy中的数组对象叫做ndarray
"""type(): 这个内置的 Python 函数告诉我们传递给它的对象的类型。像上面的代码一样，它表明 arr 是 numpy.ndarray 类型。

要创建 ndarray，我们可以将列表、元组或任何类似数组的对象传递给 array() 方法，然后它将被转换为 ndarray："""
array_1=np.array((1,2,3,4))
type(array_1)

numpy.ndarray

In [12]:
#0-D数组或者叫Scalars标量
array_2=np.array(61)
print(array_2)

61


In [21]:
#1-D数组，2-D数组，3-D数组很容易理解的是他们的元素便是上一维度的数组作为元素构成
array_3=np.array([1,2,3,4])
array_4=np.array([array_3,array_3])
array_5=np.array([array_4,array_4])
array_6=np.array([[[[1,2,3],[1,23,4]],[[1,23,4],[1,23,4]]],[[[1,2,3,],[1,2,3,]],[[1,2,34],[1,2,4,]]]])
#如果数组的所有子元素长度和类型一致，NumPy 会将其视为多维数组，并且不会在输出中显示 list 关键字。
#如果数组的子元素长度不一致，NumPy 会将这些元素视为对象数组 (dtype=object)，并在输出中显示 list 关键字。
array_7=np.array([array_5,array_5])
print(array_3)
print(array_4)
print(array_5)
print(array_6)
print(array_7)

[1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]]
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
[[[[ 1  2  3]
   [ 1 23  4]]

  [[ 1 23  4]
   [ 1 23  4]]]


 [[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2 34]
   [ 1  2  4]]]]
[[[[1 2 3 4]
   [1 2 3 4]]

  [[1 2 3 4]
   [1 2 3 4]]]


 [[[1 2 3 4]
   [1 2 3 4]]

  [[1 2 3 4]
   [1 2 3 4]]]]



在 NumPy 中，对象数组和普通数组（也称为数值数组）有以下几个主要区别：

1. 数据类型
普通数组：所有元素的类型必须相同，并且数组中的元素类型是固定的，如整数、浮点数、布尔值等。NumPy 会自动推断并统一数组的数据类型。
对象数组：允许每个元素有不同的类型。元素可以是任意 Python 对象，如整数、浮点数、字符串、列表、元组等。对象数组的元素类型被视为 Python 的 object。
2. 内存布局
普通数组：由于所有元素类型相同，NumPy 能够在内存中以连续的块来存储数据，这样访问速度更快，性能更好。
对象数组：每个元素是一个指向 Python 对象的指针。对象数组中的元素不是连续存储的，因此访问速度较慢，性能较差。
3. 操作支持
普通数组：支持大多数 NumPy 操作和函数，如矢量化运算、广播、数学运算等。这些操作在普通数组上非常高效。
对象数组：许多 NumPy 操作和函数不适用于对象数组，因为这些操作依赖于统一的数据类型和内存布局。对对象数组的操作通常会退化为逐个元素的操作，性能较差。
4. 用途
普通数组：适用于需要高效数值计算和数据处理的场景，如科学计算、数据分析、机器学习等。
对象数组：适用于需要存储和处理异构数据的场景，如包含多种数据类型的列表、复杂的嵌套结构等。

In [23]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#使用ndim来获取数组的维度
print(a.ndim) 
print(b.ndim) 
print(c.ndim) 
print(d)
#使用ndmin来创造数组
e=np.array([1,23,4],ndmin=5)
print(e)

0
1
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[[[ 1 23  4]]]]]


In [31]:
#学习使用索引对n-D数组进行访问
f=np.array([[[[1,2,3],[1,23,4]],[[1,23,4],[1,23,4]]],[[[1,2,3,],[1,2,3,]],[[1,2,34],[1,2,4,]]]])
print(f[1,1])
print(f[1,1,-1])#这里的负数就是倒过来读-1是倒数第一个元素
print(f.ndim)

[[ 1  2 34]
 [ 1  2  4]]
[1 2 4]
4


裁切数组
python 中裁切的意思是将元素从一个给定的索引带到另一个给定的索引。

我们像这样传递切片而不是索引：[start：end]。

我们还可以定义步长，如下所示：[start：end：step]。

如果我们不传递 start，则将其视为 0。

如果我们不传递 end，则视为该维度内数组的长度。

如果我们不传递 step，则视为 1。

In [39]:
#数组的裁切
print(f[0:2:1])#显然的是我们这里是左闭右开的裁剪的方式
print(f[:2])
print(f[0:])
g=np.array([1,2,3,4,5,6,7])
print(g[::2])

[[[[ 1  2  3]
   [ 1 23  4]]

  [[ 1 23  4]
   [ 1 23  4]]]


 [[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2 34]
   [ 1  2  4]]]]
[[[[ 1  2  3]
   [ 1 23  4]]

  [[ 1 23  4]
   [ 1 23  4]]]


 [[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2 34]
   [ 1  2  4]]]]
[[[[ 1  2  3]
   [ 1 23  4]]

  [[ 1 23  4]
   [ 1 23  4]]]


 [[[ 1  2  3]
   [ 1  2  3]]

  [[ 1  2 34]
   [ 1  2  4]]]]
[1 3 5 7]


In [54]:
#使用一下负裁剪的方式满足仍然是左闭右开的方式
print(g[-5:-1:1])
#多维数组的裁剪的方式
f=np.array([[[[1,2,3],[1,23,4]],[[1,23,4],[1,23,4]]],[[[1,2,3],[1,2,3]],[[1,2,34],[1,2,4]]]])
print(f[1,1,1,::1])

[3 4 5 6]
[1 2 4]


对于多维数组的裁剪很容易理解就是索引加上裁剪

Python 中的数据类型
默认情况下，Python 拥有以下数据类型：

strings - 用于表示文本数据，文本用引号引起来。例如 "ABCD"。
integer - 用于表示整数。例如 -1, -2, -3。
float - 用于表示实数。例如 1.2, 42.42。
boolean - 用于表示 True 或 False。
complex - 用于表示复平面中的数字。例如 1.0 + 2.0j，1.5 + 2.5j。
NumPy 中的数据类型
NumPy 有一些额外的数据类型，并通过一个字符引用数据类型，例如 i 代表整数，u 代表无符号整数等。

以下是 NumPy 中所有数据类型的列表以及用于表示它们的字符。

i - 整数
b - 布尔
u - 无符号整数
f - 浮点
c - 复合浮点数
m - timedelta
M - datetime
O - 对象
S - 字符串
U - unicode 字符串
V - 固定的其他类型的内存块 ( void )

In [55]:
#NumPy 数组对象有一个名为 dtype 的属性，该属性返回数组的数据类型：
t=np.array([1,2,3,4,5,6])
print(t.dtype)

int32


用已定义的数据类型创建数组
我们使用 array() 函数来创建数组，该函数可以使用可选参数：dtype，它允许我们定义数组元素的预期数据类型：

In [61]:
t=np.array([1,2,34,56,7],dtype='S')
t1=np.array(t,dtype='i4')
t2=np.array([1,2,3,4],dtype='i8')
print(t)
print(t1.dtype)
print(t2.dtype)
#i后面的数字是你是使用的多少字节的整数的类型

[b'1' b'2' b'34' b'56' b'7']
int32
int64


假如值无法转换会怎样？
如果给出了不能强制转换元素的类型，则 NumPy 将引发 ValueError。

ValueError：在 Python 中，如果传递给函数的参数的类型是非预期或错误的，则会引发 ValueError。

In [62]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [69]:
a=np.array([1.1,1.2,1.3,1.4,1.5],dtype='f')
b=a.astype('i')#使用自动转化类型的函数astype是会返回一个数组
print(a)
print(a.dtype)
print(b)
print(b.dtype)
c=b.astype(bool)
print(c)
print(c.dtype)

[1.1 1.2 1.3 1.4 1.5]
float32
[1 1 1 1 1]
int32
[ True  True  True  True  True]
bool


副本和视图之间的区别
副本和数组视图之间的主要区别在于副本是一个新数组，而这个视图只是原始数组的视图。

副本拥有数据，对副本所做的任何更改都不会影响原始数组，对原始数组所做的任何更改也不会影响副本。

视图不拥有数据，对视图所做的任何更改都会影响原始数组，而对原始数组所做的任何更改都会影响视图。类似与c++的引用和副本

In [71]:
a=np.array([1,23,4,5,6],dtype='i')
b=a.copy()
c=a.view()
a[0]=64
print(a)
print(b)
print(c)#所谓的视图就是引用
#如何检查这个数组是不是拥有数据原始数组才拥有数据副本也算原始的数组
#使用base来检查
print(b.base)
print(c.base)
#如果拥有数据那么返回的结果会是一个None的结果并不是则返回原始数组

[64 23  4  5  6]
[ 1 23  4  5  6]
[64 23  4  5  6]
None
[64 23  4  5  6]


数组的形状
数组的形状是每个维中元素的数量。

获取数组的形状
NumPy 数组有一个名为 shape 的属性，该属性返回一个元组，每个索引具有相应元素的数量。

In [72]:
#使用shape
print(f.shape)#这个数组有四个维度维度的元素个数分别为2，2，2，3

(2, 2, 2, 3)


数组重塑
重塑意味着更改数组的形状。

数组的形状是每个维中元素的数量。

通过重塑，我们可以添加或删除维度或更改每个维度中的元素数量。

In [84]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
c=a.reshape(2,3,1)#来解析一下这个的过程这个就相当与最后一个使用的是1则用1一个元素构成基本的元素然后前面是三就用三个后面的1构成一个倒数第二为的元素的的基本元素
print(b)
print(c)
#如果元素的数量是错误的话他是会返回value_error的错误的
d=np.array([[1,2,3],[1,2,3]])
e=d.reshape(2,3,1)
g=e
d[0,1]=5
print(e)
print(e.base)#值得注意的是e并不拥有数据他只是一个视图
print(g.base)
print(g.reshape(-1))
print(d.reshape(2,-1,1))
#注意我们只能使用一个-1来表示一个未知维度让python自己计算出来，对于维度的重塑他都是展开后在重塑的
#数组的展开就是重塑为一维数组的过程

[[1 2 3]
 [4 5 6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[1]
  [5]
  [3]]

 [[1]
  [2]
  [3]]]
[[1 5 3]
 [1 2 3]]
[[1 5 3]
 [1 2 3]]
[1 5 3 1 2 3]
[[[1]
  [5]
  [3]]

 [[1]
  [2]
  [3]]]


数组迭代
迭代意味着逐一遍历元素。

当我们在 numpy 中处理多维数组时，可以使用 python 的基本 for 循环来完成此操作。

如果我们对 1-D 数组进行迭代，它将逐一遍历每个元素。

In [87]:
f=np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
for x in f:
    for y in x: 
                print(y)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


使用 nditer() 迭代数组
函数 nditer() 是一个辅助函数，从非常基本的迭代到非常高级的迭代都可以使用。它解决了我们在迭代中面临的一些基本问题，让我们通过例子进行介绍。

迭代每个标量元素
在基本的 for 循环中，迭代遍历数组的每个标量，我们需要使用 n 个 for 循环，对于具有高维数的数组可能很难编写。

实例
遍历以下 3-D 数组：

In [89]:
for x in np.nditer(f):
    print(x)
    #面对的是一个高级维度的矩阵的时候需要输出他的最低维度的矩阵的元素的时候这样的可能需要写很多for in的循环但是这样我们就可以简单写出

1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4


迭代不同数据类型的数组
我们可以使用 op_dtypes 参数，并传递期望的数据类型，以在迭代时更改元素的数据类型。

NumPy 不会就地更改元素的数据类型（元素位于数组中），因此它需要一些其他空间来执行此操作，该额外空间称为 buffer，为了在 nditer() 中启用它，我们传参 flags=['buffered']。

In [96]:
a=np.array([[12,1,12,1],[1,2,3,4]])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'12'
b'1'
b'12'
b'1'
b'1'
b'2'
b'3'
b'4'


In [104]:
# 创建一个二维数组
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

# 使用 nditer 遍历数组元素，并将元素类型转换为字节串
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
for x in np.nditer(arr[::2,::1]):#这里采用的是一个多维切片的操作方式
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
1
2
3
7
8
9


使用 ndenumerate() 进行枚举迭代
枚举是指逐一提及事物的序号。

有时，我们在迭代时需要元素的相应索引，对于这些用例，可以使用 ndenumerate() 方法。

In [106]:
for index,x in np.ndenumerate(arr):
    print(index,x)#这个是所谓的枚举迭代的方式他返回的是对应的索引以及对应的值

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


连接 NumPy 数组
连接意味着将两个或多个数组的内容放在单个数组中。

在 SQL 中，我们基于键来连接表，而在 NumPy 中，我们按轴连接数组。

我们传递了一系列要与轴一起连接到 concatenate() 函数的数组。如果未显式传递轴，则将其视为 0。

In [141]:
a=np.array([[1,2,3],[2,4,6]])
b=np.array([[1,2,3],[1,2,3]])
#ValueError: all the input arrays must have same number of dimensions
c=np.concatenate((a,b),axis=1)
#如果axis的值为1的话他是沿着行进行连接的，如果axis是0的话他是通过列进行连接的,而且的他的默认值也是0
d=np.concatenate((a,b),axis=0)
print(c)
print(c.base)#而且生成的是一个原始数据的对象
print(d)
print(np.stack((a,b),axis=1))
print(np.stack((a,b),axis=0))
print(np.dstack((a,b)))

[[1 2 3 1 2 3]
 [2 4 6 1 2 3]]
None
[[1 2 3]
 [2 4 6]
 [1 2 3]
 [1 2 3]]
[[[1 2 3]
  [1 2 3]]

 [[2 4 6]
  [1 2 3]]]
[[[1 2 3]
  [2 4 6]]

 [[1 2 3]
  [1 2 3]]]
[[[1 1]
  [2 2]
  [3 3]]

 [[2 1]
  [4 2]
  [6 3]]]


使用堆栈函数连接数组
堆栈与级联相同，唯一的不同是堆栈是沿着新轴完成的。

我们可以沿着第二个轴连接两个一维数组，这将导致它们彼此重叠，即，堆叠（stacking）。

我们传递了一系列要与轴一起连接到 concatenate() 方法的数组。如果未显式传递轴，则将其视为 0。

In [135]:
a=np.array([1,23,4])
b=np.array([2,3,4])
c=np.stack((a,b))
d=np.concatenate((a,b),axis=0)#很显然的是concatenate他是不会改变类型的
print(d)
print(c)

[ 1 23  4  2  3  4]
[[ 1 23  4]
 [ 2  3  4]]


In [136]:
e=np.stack((a,b),axis=0)#矩阵的类型也是可以不一样的
f=np.hstack((a,b))
g=np.vstack((a,b))
h=np.dstack((a,b))
print(e)
print(f)
print(g)
print(h)

[[ 1 23  4]
 [ 2  3  4]]
[ 1 23  4  2  3  4]
[[ 1 23  4]
 [ 2  3  4]]
[[[ 1  2]
  [23  3]
  [ 4  4]]]


拆分 NumPy 数组
拆分是连接的反向操作。

连接（Joining）是将多个数组合并为一个，拆分（Spliting）将一个数组拆分为多个。

我们使用 array_split() 分割数组，将要分割的数组和分割数传递给它。

In [145]:
a=np.array([1,2,34,5,6,7])
b=np.array_split(a,3)
c=np.array_split(a,7)
print(b)
print(c)

[array([1, 2]), array([34,  5]), array([6, 7])]
[array([1]), array([2]), array([34]), array([5]), array([6]), array([7]), array([], dtype=int32)]


In [146]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


搜索数组
您可以在数组中搜索（检索）某个值，然后返回获得匹配的索引。

要搜索数组，请使用 where() 方法。

In [159]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x=np.where(arr%2==0)#这个是进行查找偶数的一个搜索的数组
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [160]:
y=np.searchsorted(arr,8)

In [161]:
print(y)

7


In [150]:
print(arr)

[1 2 3 4 5 6 7 8]


In [151]:
print(np.searchsorted(arr,4,side='right'))

4


In [153]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6],side='right')
#这个返回的是每个元组数据中在数组的该插入的位置
print(x)

[1 2 3]


In [163]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


数组过滤
从现有数组中取出一些元素并从中创建新数组称为过滤（filtering）。

在 NumPy 中，我们使用布尔索引列表来过滤数组。

布尔索引列表是与数组中的索引相对应的布尔值列表。

如果索引处的值为 True，则该元素包含在过滤后的数组中；如果索引处的值为 False，则该元素将从过滤后的数组中排除。

In [ ]:
arr = np.array([61, 62, 63, 64, 65])

x = [True, False, True, False, True]

newarr = arr[x]

print(newarr)